# Generated by Django 4.0.2 on 2022-03-01 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Done_name',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Created_at_name',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created_at_verbose'),
        ),
    ]
